# Generated by Django 4.1.3 on 2022-11-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_group_name_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=100)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_1.person')),
            ],
        ),
    ]
